import datetime
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, ValidationInfo, field_validator


class StatusEnum(str, Enum):
    NEW = "New"
    PENDING = "Pending"
    LOST = "Lost"
    CONVERTED = "Converted"
    READY = "Ready"
    BLOCKED = "Blocked"


class ProspectBase(BaseModel):
    name: str = Field(..., description="Name of the prospect")
    contact_name: Optional[str] = Field(
        None, description="Contact person's name for the prospect"
    )
    status: StatusEnum = Field(..., description="Status of the prospect")
    notes: Optional[str] = Field("", description="Additional notes about the prospect")
    phone: str = Field(..., description="Phone number of the prospect")
    email: str = Field(..., description="Email address of the prospect")
    city: str = Field(..., description="City of the prospect")
    country: str = Field(..., description="Country of the prospect")
    address: str = Field(..., description="Address of the prospect")
    prospect_interest: int = Field(
        ..., ge=0, le=5, description="Prospect's interest level (0-5)"
    )
    commercial_interest: int = Field(
        ..., ge=0, le=5, description="Commercial interest level (0-5)"
    )
    last_visit: Optional[datetime.datetime] = Field(
        None, description="Datetime of last visit"
    )
    next_visit: Optional[datetime.datetime] = Field(
        None, description="Datetime of next visit"
    )
    latitude: Optional[float] = Field(None, description="Latitude of the prospect")
    longitude: Optional[float] = Field(None, description="Longitude of the prospect")
    brands: List[str] = Field(
        ..., description="List of brands associated with the prospect"
    )
    favorite: Optional[bool] = Field(False)

    @field_validator("next_visit")
    def next_visit_must_be_after_last_visit(cls, v, info: ValidationInfo):
        last_visit = info.data.get("last_visit")
        if last_visit and v and v < last_visit:
            raise ValueError("next_visit must be after last_visit")
        return v


class ProspectCreate(ProspectBase):
    """
    Model for creating a new prospect.
    ID is not required (usually generated by DB).
    """

    pass


class ProspectUpdate(BaseModel):
    """
    Model for updating a prospect.
    All fields are optional.
    """

    name: Optional[str] = Field(None, description="Name of the prospect")
    contact_name: Optional[str] = Field(
        None, description="Contact person's name for the prospect"
    )
    status: Optional[StatusEnum] = Field(None, description="Status of the prospect")
    notes: Optional[str] = Field(
        None, description="Additional notes about the prospect"
    )
    phone: Optional[str] = Field(None, description="Phone number of the prospect")
    email: Optional[str] = Field(..., description="Email address of the prospect")
    city: Optional[str] = Field(None, description="City of the prospect")
    country: Optional[str] = Field(None, description="Country of the prospect")
    address: Optional[str] = Field(None, description="Address of the prospect")
    prospect_interest: Optional[int] = Field(
        None, ge=0, le=5, description="Prospect's interest level (0-5)"
    )
    commercial_interest: Optional[int] = Field(
        None, ge=0, le=5, description="Commercial interest level (0-5)"
    )
    last_visit: Optional[datetime.datetime] = Field(
        None, description="Datetime of last visit"
    )
    next_visit: Optional[datetime.datetime] = Field(
        None, description="Datetime of next visit"
    )
    latitude: Optional[float] = Field(None, description="Latitude of the prospect")
    longitude: Optional[float] = Field(None, description="Longitude of the prospect")
    brands: List[str] = Field(
        ..., description="List of brands associated with the prospect"
    )
    favorite: Optional[bool] = Field(None)

    @field_validator("next_visit")
    def next_visit_must_be_after_last_visit(cls, v, info: ValidationInfo):
        last_visit = info.data.get("last_visit")
        if last_visit and v and v < last_visit:
            raise ValueError("next_visit must be after last_visit")
        return v


class ProspectResponse(ProspectBase):
    """
    Model for returning a prospect (e.g., from DB).
    Includes the ID, timestamps, and rep_id.
    """

    id: str = Field(..., description="Unique identifier of the prospect")
    representative_id: str = Field(..., description="Linked representative id")
    created_at: datetime.datetime = Field(..., description="Creation timestamp")
    updated_at: datetime.datetime = Field(..., description="Last update timestamp")


class ProspectDelete(BaseModel):
    """
    Model for deleting a prospect.
    Only the ID is required.
    """

    id: str = Field(..., description="Unique identifier of the prospect to delete")
